services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Listener configs
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

      # KRaft settings
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Single-node KRaft
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
#      - backend
      - my-network

  user-notification:
    image: postgres:16
    container_name: user-notification
    restart: always
    environment:
      POSTGRES_DB: user-notification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5450:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
#      - backend
      - my-network

  user-app:
    build: .
    container_name: user-app
    depends_on:
      - kafka
      - user-notification
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-notification:5432/user-notification
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8084:8084"
    networks:
#      - backend
      - my-network

networks:
  my-network:
    name: my-network

volumes:
  db:


